### ISSUE TITLE
Failed to start service 'gui sha256: ... ' due to '(HTTP code 404) no such container - linux runtimespec devices: error gathering device information while adding custom device "/dev/fb1": lstat /dev/fb1: no such file or directory '

### ISSUE THREAD

**Issue by tim-carlo** [resin-io-projects/multicontainer-demo-rpi3#8]
I followed the description without any success. The services Proxy, Data and frontend are working fine but the service gui doesn't start. The whole issue is: 26.06.18 14:15:12 (+0000) Installed service 'gui sha256 : ... '
26.06.18 14:15:12 (+0000) Starting service 'gui sha256: ... '
26.06.18 14:15:34 (+0000) Failed to start service 'gui sha256: ... ' due to '(HTTP code 404) no such container - linux runtimespec devices: error gathering device information while adding custom device "/dev/fb1": lstat /dev/fb1: no such file or directory '

I deleted the content after gui sha256

**Comment by Mark-Howe** [comment]
Comment out Line 25 in docker-compose.yml if you're just using the HDMI connection.

**Comment by tim-carlo** [comment]
oh thanks that worked fine for me
